In [ ]:
# Import necessary libraries for date and time manipulation, timezone handling, and displaying formatted text in a notebook
from datetime import datetime
from pytz import timezone
from IPython.display import display, Markdown, HTML

# Display the first statement in green and bold
display(HTML("<p style='color:green; font-weight:bold;'>This is the first cell. Initialization and setup are done below:</p>"))

# Set IST timezone (Indian Standard Time)
ist = timezone('Asia/Kolkata')

# Get the current time in IST
current_time_ist = datetime.now(ist).strftime('%Y-%m-%d %H:%M:%S')

# Display the current IST time in bold (default color)
display(Markdown(f'**Current IST Time: {current_time_ist}**'))

**Current IST Time: 2024-11-21 17:19:43**

In [ ]:
# Importing the libraries
import pandas as pd

In [ ]:
dataset = pd.read_csv('https://raw.githubusercontent.com/9394113857/Predict-Salary-Analysis/raghu/hiring.csv')

In [ ]:
dataset.shape

(8, 4)

In [ ]:
dataset.head()

  experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [ ]:
# Replacing null values with zero in the 'experience' column
dataset['experience'].fillna(0, inplace=True)

# Replacing null values with the mean of 'test_score' in the 'test_score' column
dataset['test_score'].fillna(dataset['test_score'].mean(), inplace=True)

<ipython-input-11-aa9f7462182a>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['experience'].fillna(0, inplace=True)
<ipython-input-11-aa9f7462182a>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['test_score'].fillna(dataset['test_score'].mean(), inplace=True)

Explanation:
1.	Replace Null Values in 'experience':
•	dataset['experience'].fillna(0, inplace=True): Replaces null values in the 'experience' column with zero. The inplace=True parameter modifies the DataFrame in place.
2.	Replace Null Values in 'test_score':
•	dataset['test_score'].fillna(dataset['test_score'].mean(), inplace=True): Replaces null values in the 'test_score' column with the mean of the non-null values in the same column. The inplace=True parameter modifies the DataFrame in place.

In [ ]:
# Extracting the values of all rows and the first three columns from the DataFrame 'dataset' and assigning it to 'X'
X = dataset.iloc[:, :3]

**Explanation:**

1.	The code **X = dataset.iloc[:, :3]** extracts all rows and the first three columns of the DataFrame 'dataset' and assigns it to the variable 'X'.
2.	So, 'X' will contain the values of all rows from the first three columns of your dataset, which typically would correspond to your features (such as experience, test_score, interview_score) in the context of a multi-linear regression model.

In [ ]:
X

  experience  test_score  interview_score
0          0    8.000000                9
1          0    8.000000                6
2       five    6.000000                7
3        two   10.000000               10
4      seven    9.000000                6
5      three    7.000000               10
6        ten    7.857143                7
7     eleven    7.000000                8

In [ ]:
# Function to convert words to integer values
def convert_to_int(word):
    word_dict = {'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5, 'six': 6, 'seven': 7, 'eight': 8,
                'nine': 9, 'ten': 10, 'eleven': 11, 'twelve': 12, 'zero': 0, 0: 0}
    return word_dict[word]

Explanation:

•	convert_to_int(word): This function takes a word as input and returns its corresponding integer value based on the predefined dictionary word_dict. The dictionary maps words to their numerical representations. If the input is not found in the dictionary, it returns 0.

In [ ]:
# Applying the convert_to_int function to the 'experience' column in DataFrame 'X'
X['experience'] = X['experience'].apply(lambda x: convert_to_int(x))

Explanation:

•	X['experience']: Accesses the 'experience' column in DataFrame 'X'.

•	.apply(lambda x: convert_to_int(x)): Applies the convert_to_int function to each element in the 'experience' column using a lambda function. This transforms the words in the 'experience' column to their corresponding integer values.

In [ ]:
X

   experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [ ]:
# Extracting the values of all rows and the last column from the DataFrame 'dataset' and assigning it to 'y'
y = dataset.iloc[:, -1]

Explanation:

•	dataset.iloc[:, -1]: Selects all rows (:) and the last column (-1) from the DataFrame 'dataset'.

•	y: Represents the target variable, containing the values of all rows in the last column of the 'dataset'.

In [ ]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [ ]:
# Importing Linear Regression from scikit-learn
from sklearn.linear_model import LinearRegression

# Creating a Linear Regression model instance
regressor = LinearRegression()

Explanation:

1.	Import Linear Regression:

•	from sklearn.linear_model import LinearRegression: Imports the Linear Regression class from the scikit-learn library.

2.	Create Linear Regression Model:

•	regressor = LinearRegression(): Instantiates a Linear Regression model using the imported class. The variable regressor now holds an instance of the Linear Regression model.

In [ ]:
# Fitting the Linear Regression model with training data
regressor.fit(X, y)

LinearRegression()

Explanation:

•	regressor.fit(X, y): Fits the Linear Regression model using the training data. The features are represented by the matrix 'X', and the target variable is represented by 'y'. This step trains the model on the provided training dataset.

In [ ]:
# Calculate the accuracy score of the Linear Regression model on the training data
regressor.score(X, y)

0.9639958361860579

Explanation:

•	regressor.score(X, y): Calculates the R^2 (coefficient of determination) score, which represents the proportion of the variance in the dependent variable ('y') that is predictable from the independent variables ('X'). This method provides the accuracy score of the Linear Regression model on the training data.

In [ ]:
X # These are the inputs we have to give to model when the model is loaded ok.

   experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [ ]:
# These are y single outcome y is test results, we have given first x as train data,
# then y is test data we are looking the samples okay,
# but check actual predicted model results would near to the test results means we achieved our use-case ok.
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [ ]:
# Import the Pickle library
import pickle

Explanation:

•	import pickle: Imports the Pickle library, which is used for saving and loading Python objects, including machine learning models.

In [ ]:
# Save the trained Linear Regression model to a file using Pickle
pickle.dump(regressor, open('multi_linear_regression_salary_prediction.pkl', 'wb'))

Explanation:

pickle.dump(regressor, open('multi_linear_regression_salary_prediction.pkl', 'wb')): Saves the trained Linear Regression model (regressor) to a file named 'multi_linear_regression_salary_prediction.pkl' using Pickle in binary write mode ('wb').

In [ ]:
# Load the saved Linear Regression model for comparison
model = pickle.load(open('multi_linear_regression_salary_prediction.pkl', 'rb'))

Explanation:

•	model = pickle.load(open('multi_linear_regression_salary_prediction.pkl', 'rb')): Loads the saved Linear Regression model from the file 'multi_linear_regression_salary_prediction.pkl' using Pickle in binary read mode ('rb'). The loaded model is assigned to the variable model.

In [ ]:
# The variable 'model' holds the loaded Linear Regression model
model

LinearRegression()

This code is referencing the variable 'model' but not displaying its content. If you want to see the details of the loaded model, you can print it using print(model) or inspect its properties and methods in a Jupyter Notebook or similar environment.

In [ ]:
# Print the type of variable 'model'
type(model)

sklearn.linear_model._base.LinearRegression

This code is used to check and display the type of the variable 'model'. It helps you confirm that 'model' is an instance of the Linear Regression model or another appropriate class/type.

In [ ]:
# Use the loaded model to make predictions on new data
result = model.predict([[2, 9, 6]])
print(result)

[53290.89255945]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

Explanation:

•	model.predict([[2, 9, 6]]): Uses the loaded Linear Regression model (model) to make predictions on new data. In this case, it predicts the target variable for the input features [2, 9, 6].

•	print(result): Prints the predicted result.

# User Input:

In [ ]:
# !pip install rich

In [ ]:
# Import necessary libraries
import pickle
from rich.console import Console

# Load the pre-trained Linear Regression model
model = pickle.load(open('multi_linear_regression_salary_prediction.pkl', 'rb'))  # Replace 'your_model_path.pkl' with the actual path to your model file

# Get user input for experience, test score, and interview score
Value_1 = float(input("Enter Experience | Eg: 2 "))
Value_2 = float(input("Enter Test Score | Eg: 9 "))
Value_3 = float(input("Enter Interview Score | Eg: 6 "))
print()

# Create a Console instance for rich text printing
console = Console()

# Print the section separator
console.print("=================================================")

# Print the entered values in bold green
console.print(f"The entered values: [bold green]{Value_1}[/bold green], [bold green]{Value_2}[/bold green], [bold green]{Value_3}[/bold green]")

# Use the model to predict based on the entered values
predicted = model.predict([[Value_1, Value_2, Value_3]])

# Print the predicted value from the model in bold green
console.print(f"The predicted value from the model: [bold green]{predicted[0]}[/bold green]")

# Print the section separator
console.print("=================================================")

Enter Experience | Eg: 2 2
Enter Test Score | Eg: 9 9
Enter Interview Score | Eg: 6 6

=================================================

The entered values: 2.0, 9.0, 6.0

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

The predicted value from the model: 53290.892559447646

=================================================

Explanation:

•	This script loads a pre-trained Linear Regression model, takes user input for experience, test score, and interview score, and then uses the model to predict the salary based on the entered values. The results are printed using the rich text formatting provided by the rich library. The section separators help visually separate different parts of the output.

#Regards
Raghu

In [ ]:
import pandas as pd

# Creating a DataFrame to present information in table format
regression_summary_table = pd.DataFrame(columns=['SNo', 'Type', 'Task', 'Target Variable', 'Data Type'])

# Adding information for the regression problem with supervised learning
regression_summary_table.loc[0] = [1, 'Supervised Learning', 'Multi-linear Regression', 'Salary', 'Labeled']

# Displaying the information in table format
print(regression_summary_table.to_markdown(index=False, tablefmt="pretty", colalign=("center",)))

+-----+---------------------+-------------------------+-----------------+-----------+
| SNo |        Type         |          Task           | Target Variable | Data Type |
+-----+---------------------+-------------------------+-----------------+-----------+
|  1  | Supervised Learning | Multi-linear Regression |     Salary      |  Labeled  |
+-----+---------------------+-------------------------+-----------------+-----------+

In [ ]:
# https://chat.openai.com/c/6dec87ca-c07a-4abf-9b5b-17a9887f6cb2

In [ ]:
# Cell 2: Current Date and Time in IST

# Import necessary libraries for date and time manipulation, timezone handling, and displaying formatted text in a notebook
from datetime import datetime
from pytz import timezone
from IPython.display import display, Markdown, HTML

# Display the statement "All cells above have been executed..." in red and bold
display(HTML("<p style='color:red; font-weight:bold;'>All cells above have been executed. Below is the current date and time in IST:</p>"))

# Set IST timezone
ist = timezone('Asia/Kolkata')

# Get current time in IST
now_ist = datetime.now(ist)

# Format the current date and time separately
formatted_date = now_ist.strftime('%Y-%m-%d')
formatted_time = now_ist.strftime('%H:%M:%S %Z%z')

# Display the current date in bold (default black color)
display(Markdown(f'**Date: {formatted_date}**'))

# Display the current time in bold (default black color)
display(Markdown(f'**Time: {formatted_time}**'))

**Date: 2024-11-21**

**Time: 17:20:00 IST+0530**

In [ ]:
# Import necessary libraries for date and time manipulation, timezone handling, and displaying formatted text in a notebook
from datetime import datetime
from pytz import timezone
from IPython.display import display, Markdown, HTML

# Track the time when the first cell is executed
first_cell_time = datetime.now()

# Display the first statement in green and bold
display(HTML("<p style='color:green; font-weight:bold;'>This is the first cell. Initialization and setup are done below:</p>"))

# Set IST timezone (Indian Standard Time)
ist = timezone('Asia/Kolkata')

# Get the current time in IST
current_time_ist = datetime.now(ist).strftime('%Y-%m-%d %H:%M:%S')

# Display the current IST time in bold (default color)
display(Markdown(f'**Current IST Time: {current_time_ist}**'))

# ----------------------------------------

# Cell 2: Current Date and Time in IST

# Track the time when the last cell is executed
last_cell_time = datetime.now()

# Display the statement "All cells above have been executed..." in red and bold
display(HTML("<p style='color:red; font-weight:bold;'>All cells above have been executed. Below is the current date and time in IST:</p>"))

# Set IST timezone
ist = timezone('Asia/Kolkata')

# Get current time in IST
now_ist = datetime.now(ist)

# Format the current date and time separately
formatted_date = now_ist.strftime('%Y-%m-%d')
formatted_time = now_ist.strftime('%H:%M:%S %Z%z')

# Display the current date in bold (default black color)
display(Markdown(f'**Date: {formatted_date}**'))

# Display the current time in bold (default black color)
display(Markdown(f'**Time: {formatted_time}**'))

# ===============================================

# Calculate the time difference between first and last cell execution
time_diff = last_cell_time - first_cell_time

# Display the title for time taken in execution in orange and bold
display(HTML("<p style='color:orange; font-weight:bold;'>Total Time Taken for Notebook Execution:</p>"))

# Display the time difference in bold (black color)
display(Markdown(f'**{str(time_diff)}**'))

**Current IST Time: 2024-11-21 17:20:00**

**Date: 2024-11-21**

**Time: 17:20:00 IST+0530**

**0:00:00.012061**