In [ ]:
# Cell 1: Initialization and Setup

# Import necessary libraries for date and time manipulation, timezone handling, and displaying formatted text in a notebook
from datetime import datetime
from pytz import timezone
from IPython.display import display, Markdown

# Print statement indicating this is the first cell
print("This is the first cell. Initialization and setup are done below:")

# Set IST timezone
ist = timezone('Asia/Kolkata')

# Date and time to display (Example: a specified past date and time)
specified_date = '2024-06-05'
specified_time = '13:09:34 IST+0530'

# Display the specified date in bold
display(Markdown(f'**Date: {specified_date}**'))

# Display the specified time in bold
display(Markdown(f'**Time: {specified_time}**'))

This is the first cell. Initialization and setup are done below:

**Date: 2024-06-05**

**Time: 13:09:34 IST+0530**

In [ ]:
# Import the Pandas library and use the alias 'pd' for convenience
import pandas as pd

In [ ]:
# Read a CSV file into a Pandas DataFrame
# The 'movies' DataFrame will contain the data from the specified CSV file
# The CSV file is loaded from a URL in this case
movies = pd.read_csv('https://raw.githubusercontent.com/Chando0185/movie_recommender_system/main/dataset.csv')

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB

In [ ]:
# Check the dimensions of the dataframe 'movies'
movies.shape

(10000, 9)

In [ ]:
# Display the first 10 rows of the 'movies' DataFrame
# The 'head()' method is used to show a specified number of rows from the beginning of the DataFrame
# In this case, it displays the first 10 rows
movies.head(10)

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
5,667257,Impossible Things,"Family,Drama",es,"Matilde is a woman who, after the death of her...",14.358,2021-06-17,8.6,255
6,129,Spirited Away,"Animation,Family,Fantasy",ja,"A young girl, Chihiro, becomes trapped in a st...",92.056,2001-07-20,8.5,13093
7,730154,Your Eyes Tell,"Romance,Drama",ja,"A tragic accident lead to Kaori's blindness, b...",51.345,2020-10-23,8.5,339
8,372754,Dou kyu sei – Classmates,"Romance,Animation",ja,"Rihito Sajo, an honor student with a perfect s...",14.285,2016-02-20,8.5,239
9,372058,Your Name.,"Romance,Animation,Drama",ja,High schoolers Mitsuha and Taki are complete s...,158.270,2016-08-26,8.5,8895

In [ ]:
# Generate descriptive statistics of the 'movies' DataFrame
# The 'describe()' method provides summary statistics of the numeric columns in the DataFrame
movies.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [ ]:
# Display concise information about the 'movies' DataFrame
# The 'info()' method provides information about the DataFrame, including data types, non-null values, and memory usage
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB

In [ ]:
# Check for null values in the 'movies' DataFrame
# The 'isnull()' method returns a DataFrame of the same shape as 'movies' with True where null values are present, and False otherwise
# The 'sum()' method then sums up the True values (True is considered as 1) for each column, providing the count of null values in each column
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

Feature Selection Part

In [ ]:
# Retrieve the column names of the 'movies' DataFrame
# The 'columns' attribute returns an Index object representing the column labels
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
# Select a subset of columns in the 'movies' DataFrame
# The DataFrame is updated to include only the specified columns: 'id', 'title', 'overview', and 'genre'
movies = movies[['id', 'title', 'overview', 'genre']]

In [ ]:
movies

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy"
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War"
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama"
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime"

In [ ]:
# Create a new column 'tags' in the DataFrame 'movies'
# Concatenate the 'overview' and 'genre' columns to form the 'tags' column
movies['tags'] = movies['overview'] + movies['genre']

In [ ]:
movies

,id,title,overview,genre,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

In [ ]:
# Create a new DataFrame 'new_data' by dropping specified columns from the 'movies' DataFrame
# The 'drop()' method is used to remove the 'overview' and 'genre' columns from 'movies'
# The result is stored in 'new_data'
new_data = movies.drop(columns=['overview', 'genre'])

In [ ]:
new_data

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...

In [ ]:
# Import the CountVectorizer class from the sklearn.feature_extraction.text module
from sklearn.feature_extraction.text import CountVectorizer

1.	The CountVectorizer class in scikit-learn is used to convert a collection of text documents into a matrix of token counts.
2.	It tokenizes the text data, builds a vocabulary of known words (tokens), and transforms the text data into a sparse matrix where each row represents a document and each column represents a word in the vocabulary.
3.	Each cell in the matrix contains the count of occurrences of the corresponding word in the document.
4.	This process is useful for preparing text data for machine learning algorithms that require numerical input, such as classification or clustering algorithms.
5.	It allows the algorithms to work with text data by representing it in a format that they can understand and process.

In [ ]:
# Create an instance of CountVectorizer
# The 'max_features' parameter sets the maximum number of features (words) to be included in the vocabulary, limiting to 10,000 in this case
# The 'stop_words' parameter is set to 'english' to exclude common English stop words from the vocabulary
cv = CountVectorizer(max_features=10000, stop_words='english')

**This code creates an instance of the CountVectorizer class from scikit-learn. Here's a breakdown of the parameters used:**

**1.	max_features:** This parameter specifies the maximum number of features (words) to be included in the vocabulary. In this case, it's set to 10,000, meaning only the top 10,000 most frequent words will be used as features.

**2.	stop_words:** This parameter specifies the list of stop words to be excluded from the vocabulary. By setting it to 'english', common English stop words such as "the", "is", "and", etc., will be ignored during tokenization.

**Overview:**

This instance of CountVectorizer is now configured to tokenize text data, build a vocabulary of up to 10,000 words, and exclude common English stop words.

In [ ]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [ ]:
# Use the 'fit_transform' method of CountVectorizer to convert text data into a bag-of-words representation
# The 'new_data['tags'].values.astype('U')' extracts the 'tags' column from 'new_data' and ensures it is of Unicode type
# The resulting sparse matrix is converted to a dense NumPy array using 'toarray()'
vector = cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [ ]:
# Check the shape of the 'vector' array
# The 'shape' attribute provides the dimensions of the array (number of rows and columns)
vector.shape

(10000, 10000)

In [ ]:
# Import the cosine_similarity function from the sklearn.metrics.pairwise module
from sklearn.metrics.pairwise import cosine_similarity

1.	The code imports the cosine_similarity function from the sklearn.metrics.pairwise module.
2.	This function is used to compute the cosine similarity between samples in two matrices.
3.	In the context of natural language processing (NLP) or text analysis, cosine similarity is often used to measure the similarity between two text documents represented as vectors in a high-dimensional space.
4.	It calculates the cosine of the angle between two vectors, providing a measure of similarity regardless of their magnitudes.

In [ ]:
# 36 seconds taken
# Calculate the cosine similarity matrix using the 'cosine_similarity' function
# The 'vector' array is used as input, representing the bag-of-words representation of the 'tags' column
# The resulting 'similarity' matrix contains pairwise cosine similarities between rows (documents)
similarity = cosine_similarity(vector)

In [ ]:
# It seems like you want to inspect or display the calculated cosine similarity matrix.
similarity

array([[1.        , 0.05634362, 0.12888482, ..., 0.07559289, 0.11065667,
        0.06388766],
       [0.05634362, 1.        , 0.07624929, ..., 0.        , 0.03636965,
        0.        ],
       [0.12888482, 0.07624929, 1.        , ..., 0.02273314, 0.06655583,
        0.08645856],
       ...,
       [0.07559289, 0.        , 0.02273314, ..., 1.        , 0.03253   ,
        0.02817181],
       [0.11065667, 0.03636965, 0.06655583, ..., 0.03253   , 1.        ,
        0.0412393 ],
       [0.06388766, 0.        , 0.08645856, ..., 0.02817181, 0.0412393 ,
        1.        ]])

In [ ]:
# Find the index of the movie with the title "The Godfather" in the 'new_data' DataFrame
# The result is the index of the first occurrence of the movie in the DataFrame
index_of_godfather = new_data[new_data['title'] == "The Godfather"].index[0]

In [ ]:
# Calculate the cosine similarity matrix and find the index of a specific movie (e.g., the third movie)
index_of_movie = new_data[new_data['title'] == "The Godfather"].index[0]

# Get the cosine similarity values for the specified movie
distance = sorted(list(enumerate(similarity[index_of_movie])), reverse=True, key=lambda vector: vector[1])

# Print the titles of the top 5 most similar movies
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City

This code calculates the cosine similarity between the specified movie and all other movies, then prints the titles of the top 5 most similar movies.

In [ ]:
def recommend(movie_title):
    # Find the index of the specified movie in the 'new_data' DataFrame
    index = new_data[new_data['title'] == movie_title].index[0]

    # Calculate the cosine similarity values for the specified movie
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector: vector[1])

    # Print the titles of the top 5 most similar movies
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

This function takes a movie title as input, finds its index, calculates cosine similarity values, and then prints the titles of the top 5 most similar movies.

In [ ]:
# Call the recommend function with the movie title "Iron Man"
recommend("Iron Man")

Iron Man
Iron Man 3
Guardians of the Galaxy Vol. 2
Avengers: Age of Ultron
Star Wars: Episode III - Revenge of the Sith

This code invokes the recommend function with the movie title "Iron Man," initiating the process of finding and printing the titles of the top 5 most similar movies.

In [ ]:
# Import the pickle module for working with Python object serialization
import pickle

In [ ]:
# Serialize and save the 'new_data' DataFrame using pickle
# The 'wb' mode is used for writing in binary mode
pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [ ]:
# Serialize and save the 'similarity' matrix using pickle
# The 'wb' mode is used for writing in binary mode
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [ ]:
# Load the serialized 'new_data' DataFrame from the file 'movies_list.pkl' using pickle
# The 'rb' mode is used for reading in binary mode
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

In [ ]:
import pickle

def load_data():
    # Load the serialized 'new_data' DataFrame and 'similarity' matrix using pickle
    loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))
    loaded_similarity = pickle.load(open('similarity.pkl', 'rb'))

    return loaded_movies_list, loaded_similarity

def recommend_movie(input_movie, movies_data, similarity_matrix):
    # Find the index of the input movie in the DataFrame
    input_index = movies_data[movies_data['title'] == input_movie].index[0]

    # Calculate the cosine similarity values for the input movie
    distance = sorted(list(enumerate(similarity_matrix[input_index])), reverse=True, key=lambda vector: vector[1])

    # Print the titles of the top 5 most similar movies
    print(f"\nTop 5 recommendations for '{input_movie}':")
    for i in distance[1:6]:  # Exclude the first one as it's the input movie itself
        similar_movie_title = movies_data.iloc[i[0]].title
        print(similar_movie_title)

# Load the data
movies_data, similarity_matrix = load_data()

# Example usage
input_movie_title = "Iron Man"
recommend_movie(input_movie_title, movies_data, similarity_matrix)

Top 5 recommendations for 'Iron Man':
Iron Man 3
Guardians of the Galaxy Vol. 2
Avengers: Age of Ultron
Star Wars: Episode III - Revenge of the Sith
G.O.R.A.

In [ ]:
# Load the serialized 'new_data' DataFrame using pickle
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

# Display the loaded dataset
print("Loaded Dataset:")
print(loaded_movies_list)

Loaded Dataset:
          id                                          title  \
0        278                       The Shawshank Redemption
1      19404                    Dilwale Dulhania Le Jayenge
2        238                                  The Godfather
3        424                               Schindler's List
4        240                         The Godfather: Part II
...      ...                                            ...
9995   10196                             The Last Airbender
9996  331446                       Sharknado 3: Oh Hell No!
9997   13995                                Captain America
9998    2312  In the Name of the King: A Dungeon Siege Tale
9999  455957                                         Domino

                                                   tags
0     Framed in the 1940s for the double murder of h...
1     Raj is a rich, carefree, happy-go-lucky second...
2     Spanning the years 1945 to 1955, a chronicle o...
3     The true story of how businessman Oskar Schind...
4     In the continuing saga of the Corleone crime f...
...                                                 ...
9995  The story follows the adventures of Aang, a yo...
9996  The sharks take bite out of the East Coast whe...
9997  During World War II, a brave, patriotic Americ...
9998  A man named Farmer sets out to rescue his kidn...
9999  Seeking justice for his partner’s murder by an...

[10000 rows x 3 columns]

In [ ]:
import pandas as pd
from IPython.display import display

# Load the serialized 'new_data' DataFrame using pickle
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

# Add a serial number (sno) column to the DataFrame
loaded_movies_list['sno'] = range(1, len(loaded_movies_list) + 1)

# Display the loaded dataset with serial numbers in a tabular format
print("Loaded Dataset:")
display(loaded_movies_list)

Loaded Dataset:

,id,title,tags,sno
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",2
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",3
3,424,Schindler's List,The true story of how businessman Oskar Schind...,4
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,5
...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...",9996
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,9997
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...",9998
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,9999
9999,455957,Domino,Seeking justice for his partner’s murder by an...,10000

In [ ]:
import pandas as pd
from IPython.display import display

# Load the serialized 'new_data' DataFrame using pickle
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

# Add a serial number (sno) column to the DataFrame
loaded_movies_list['sno'] = range(1, len(loaded_movies_list) + 1)

# Reorganize the columns to have 'sno' as the first column
loaded_movies_list = loaded_movies_list[['sno', 'id', 'title', 'tags']]

# Display the loaded dataset with serial numbers in a tabular format
print("Loaded Dataset:")
display(loaded_movies_list)

Loaded Dataset:

,sno,id,title,tags
0,1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,2,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,4,424,Schindler's List,The true story of how businessman Oskar Schind...
4,5,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,9996,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,9997,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,9998,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,9999,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,10000,455957,Domino,Seeking justice for his partner’s murder by an...

In [ ]:
# make changes for this cell only like experiments
import pandas as pd
from IPython.display import display

# Load the serialized 'new_data' DataFrame using pickle
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

# Add a serial number (sno) column to the DataFrame
loaded_movies_list['sno'] = range(1, len(loaded_movies_list) + 1)

# Reorganize the columns to have 'sno' as the first column
loaded_movies_list = loaded_movies_list[['sno', 'id', 'title', 'tags']]

# Display the loaded dataset with serial numbers in a tabular format
print("Loaded Dataset:")
display(loaded_movies_list)

Loaded Dataset:

,sno,id,title,tags
0,1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,2,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,4,424,Schindler's List,The true story of how businessman Oskar Schind...
4,5,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,9996,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,9997,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,9998,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,9999,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,10000,455957,Domino,Seeking justice for his partner’s murder by an...

In [ ]:
# make changes for this cell only like experiments
import pandas as pd
from IPython.display import display

# Load the serialized 'new_data' DataFrame using pickle
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

# Add a serial number (sno) column to the DataFrame
loaded_movies_list['sno'] = range(1, len(loaded_movies_list) + 1)

# Reorganize the columns to have 'sno' as the first column
loaded_movies_list = loaded_movies_list[['sno', 'id', 'title', 'tags']]

# Display the loaded dataset with serial numbers in a tabular format
print("Loaded Dataset:")
display(loaded_movies_list)

Loaded Dataset:

,sno,id,title,tags
0,1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,2,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,4,424,Schindler's List,The true story of how businessman Oskar Schind...
4,5,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,9996,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,9997,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,9998,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,9999,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,10000,455957,Domino,Seeking justice for his partner’s murder by an...

Certainly! Let's start by displaying the loaded dataset in a tabular format:

In [ ]:
import pandas as pd
from IPython.display import display

# Load the serialized 'new_data' DataFrame using pickle
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

# Add a serial number (sno) column to the DataFrame
loaded_movies_list['sno'] = range(1, len(loaded_movies_list) + 1)

# Reorganize the columns to have 'sno' as the first column
loaded_movies_list = loaded_movies_list[['sno', 'id', 'title', 'tags']]

# Display the loaded dataset with serial numbers in a tabular format
print("Loaded Dataset:")
display(loaded_movies_list)

Loaded Dataset:

,sno,id,title,tags
0,1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,2,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,4,424,Schindler's List,The true story of how businessman Oskar Schind...
4,5,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,9996,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,9997,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,9998,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,9999,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,10000,455957,Domino,Seeking justice for his partner’s murder by an...

Now, let's create a function to receive custom input and provide recommendations:

In [ ]:
def custom_recommendation(user_input, movies_data, similarity_matrix):
    # Find the index of the user input in the DataFrame
    input_index = movies_data[movies_data['title'] == user_input].index[0]

    # Calculate the cosine similarity values for the user input
    distance = sorted(list(enumerate(similarity_matrix[input_index])), reverse=True, key=lambda vector: vector[1])

    # Print the titles of the top 5 most similar movies
    print(f"\nTop 5 recommendations for '{user_input}':")
    for i in distance[1:6]:  # Exclude the first one as it's the input movie itself
        similar_movie_title = movies_data.iloc[i[0]].title
        print(similar_movie_title)

Now, you can use the custom_recommendation function with your own input:

In [ ]:
# Example usage: Provide a movie title as user input
user_input_title = "The Godfather"
custom_recommendation(user_input_title, loaded_movies_list, similarity_matrix)

Top 5 recommendations for 'The Godfather':
The Godfather: Part II
Blood Ties
Joker
Bomb City
Gotti

# User Input:-

In [ ]:
import pandas as pd
import pickle
from IPython.display import display, HTML
import ipywidgets as widgets

# Load the serialized 'new_data' DataFrame using pickle
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

# Add a serial number (sno) column to the DataFrame
loaded_movies_list['sno'] = range(1, len(loaded_movies_list) + 1)

# Reorganize the columns to have 'sno' as the first column
loaded_movies_list = loaded_movies_list[['sno', 'id', 'title', 'tags']]

# Display the loaded dataset with serial numbers in a tabular format
print("Loaded Dataset:")
display(loaded_movies_list)

# Mock similarity matrix for demonstration purposes
import numpy as np
similarity_matrix = np.random.rand(len(loaded_movies_list), len(loaded_movies_list))

# Function to provide custom recommendations
def custom_recommendation(user_input, movies_data, similarity_matrix):
    try:
        # Find the index of the user input in the DataFrame
        input_index = movies_data[movies_data['title'].str.lower() == user_input.lower()].index[0]

        # Calculate the cosine similarity values for the user input
        distance = sorted(list(enumerate(similarity_matrix[input_index])), reverse=True, key=lambda vector: vector[1])

        # Get the titles of the top 5 most similar movies
        recommendations = []
        for idx, i in enumerate(distance[1:6], 1):  # Exclude the first one as it's the input movie itself
            similar_movie_title = movies_data.iloc[i[0]].title
            recommendations.append({
                'S.No': idx,
                'Recommended Movie': similar_movie_title,
                'Similarity Score': round(i[1], 2)
            })

        # Display recommendations in a table format with borders
        recommendations_df = pd.DataFrame(recommendations)
        display(HTML(f"<h4>Recommendations for: <span style='color: blue;'>{user_input}</span></h4>"))
        display(HTML(recommendations_df.to_html(index=False, border=1, classes='table-bordered')))

    except IndexError:
        print("Movie title not found. Please try a different title.")

# Create an input text box widget for user input
user_input_widget = widgets.Text(
    value='',
    placeholder='Enter a movie title',
    description='Movie Title:',
    disabled=False
)

# Display the input widget
display(user_input_widget)

# Function to handle the input after the user submits
def on_submit(change):
    user_input_title = user_input_widget.value
    custom_recommendation(user_input_title, loaded_movies_list, similarity_matrix)

# Attach the function to the text widget
user_input_widget.on_submit(on_submit)

Loaded Dataset:

,sno,id,title,tags
0,1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,2,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,4,424,Schindler's List,The true story of how businessman Oskar Schind...
4,5,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,9996,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,9997,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,9998,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,9999,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,10000,455957,Domino,Seeking justice for his partner’s murder by an...

Text(value='', description='Movie Title:', placeholder='Enter a movie title')

In [ ]:
import pickle
from IPython.display import display
from prettytable import PrettyTable

# Load the serialized 'new_data' DataFrame using pickle
loaded_movies_list = pickle.load(open('movies_list.pkl', 'rb'))

# Load the serialized 'similarity' matrix using pickle
similarity_matrix = pickle.load(open('similarity.pkl', 'rb'))

# Add a serial number (sno) column to the DataFrame
loaded_movies_list['sno'] = range(1, len(loaded_movies_list) + 1)

# Reorganize the columns to have 'sno' as the first column
loaded_movies_list = loaded_movies_list[['sno', 'id', 'title', 'tags']]

# Display the loaded dataset with serial numbers in a tabular format
print("Loaded Dataset:")
display(loaded_movies_list)

# Take input from the user
user_input_title = input("\nEnter a movie title for recommendations: ")

# Find the index of the user input in the DataFrame
input_index = loaded_movies_list[loaded_movies_list['title'] == user_input_title].index[0]

# Calculate the cosine similarity values for the user input
distance = sorted(list(enumerate(similarity_matrix[input_index])), reverse=True, key=lambda vector: vector[1])

# Create a PrettyTable for recommendations
recommendations_table = PrettyTable()
recommendations_table.field_names = ["Rank", "Title"]

# Print the titles of the top 5 most similar movies
print(f"\nTop 5 recommendations for '{user_input_title}':")
for rank, i in enumerate(distance[1:6], start=1):  # Exclude the first one as it's the input movie itself
    similar_movie_title = loaded_movies_list.iloc[i[0]].title
    recommendations_table.add_row([rank, similar_movie_title])

# Print recommendations in a table format
print(recommendations_table)

Loaded Dataset:

,sno,id,title,tags
0,1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,2,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,4,424,Schindler's List,The true story of how businessman Oskar Schind...
4,5,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,9996,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,9997,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,9998,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,9999,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,10000,455957,Domino,Seeking justice for his partner’s murder by an...

Enter a movie title for recommendations: Domino

Top 5 recommendations for 'Domino':
+------+-------------------+
| Rank |       Title       |
+------+-------------------+
|  1   | One for the Money |
|  2   |  Man on the Moon  |
|  3   |    Batman: Hush   |
|  4   |       Twelve      |
|  5   |       Felon       |
+------+-------------------+

This code uses the PrettyTable library to create a table with columns "Rank" and "Title" for the top 5 recommendations.

1.	Brubaker:

•	Most similar to "The Shawshank Redemption."

2.	The Woodsman:

•	Second most similar.

3.	A Prophet:

•	Third most similar.

4.	Gotti:

•	Fourth most similar.

5.	Cool Hand Luke:

•	Fifth most similar.

These movies share common features or themes based on the cosine similarity scores.

1.	This scenario falls under the category of a recommendation system, which is a type of unsupervised learning.
2.	In unsupervised learning, the algorithm works with unlabeled data to find patterns or relationships without explicit guidance.
3.	In this case, the algorithm uses cosine similarity to identify movies that are similar to the user's input, "The Shawshank Redemption," and recommends them based on those similarities.
4.	Specifically, this can be considered a content-based recommendation system.
5.	The recommendations are made by comparing the content or features of movies, and the algorithm suggests movies with similar characteristics to the input movie.
6.	 Content-based recommendation systems are a type of recommendation system that relies on the intrinsic properties of items (in this case, movies) rather than on user preferences or collaborative filtering.

# Summary of ML Task

In [ ]:
import pandas as pd

# Creating a DataFrame to present information in table format
summary_table = pd.DataFrame(columns=['SNo', 'Category', 'Problem', 'Learning Approach', 'Data Type'])

# Adding information for the movie recommendation case
summary_table.loc[0] = [1, 'Recommendation System', 'Movie Recommendations', 'Unsupervised Learning', 'Unlabeled']

# Displaying the information in table format
print(summary_table.to_markdown(index=False, tablefmt="pretty", colalign=("center",)))

In [ ]:
# https://chat.openai.com/c/f49fc695-3f22-4896-aef8-258b59701ecf

In [ ]:
# Import necessary libraries for date and time manipulation, timezone handling, and displaying formatted text in a notebook
from datetime import datetime
from pytz import timezone
from IPython.display import display, Markdown

# Set IST timezone
ist = timezone('Asia/Kolkata')

# Get current time in IST
now_ist = datetime.now(ist)

# Format the date and time separately
formatted_date = now_ist.strftime('%Y-%m-%d')
formatted_time = now_ist.strftime('%H:%M:%S %Z%z')

# Print statement indicating this is the last cell and all above cells have been executed
print("All cells above have been executed. Below is the current date and time in IST:")

# Display the date in bold
display(Markdown(f'**Date: {formatted_date}**'))

# Display the time in bold
display(Markdown(f'**Time: {formatted_time}**'))

# Interview Preparation: Q&A based on the Notebook

This section provides a Q&A based on the steps performed in the notebook, which can be helpful for explaining the project in an interview.

**Q1: What was the first step in the notebook?**

**A1:** The first step involved initializing and setting up the environment by importing necessary libraries (`datetime`, `pytz`, `IPython.display`) for handling dates, times, timezones, and displaying formatted text.

**Q2: How was the dataset loaded into the notebook?**

**A2:** The dataset was loaded into a pandas DataFrame named `movies` by reading a CSV file from a URL using `pd.read_csv()`.

**Q3: What initial exploration steps were performed on the dataset?**

**A3:**
1. The `movies.info()` method was used to get a concise summary of the DataFrame, including data types and non-null counts.
2. The `movies.shape` attribute was used to check the dimensions (number of rows and columns) of the DataFrame.
3. The `movies.head(10)` method was used to display the first 10 rows to get a glimpse of the data.
4. The `movies.describe()` method was used to generate descriptive statistics of the numerical columns.
5. The `movies.isnull().sum()` method was used to check for and count any missing (null) values in each column.

**Q4: Which columns were selected for the feature selection part of the project?**

**A4:** The columns selected were 'id', 'title', 'overview', and 'genre'.

**Q5: How was the 'tags' column created, and what does it contain?**

**A5:** The 'tags' column was created by concatenating the 'overview' and 'genre' columns. It contains a combination of the movie's overview and its genre(s).

**Q6: After creating the 'tags' column, which columns were dropped from the DataFrame?**

**A6:** The 'overview' and 'genre' columns were dropped, as their information was combined into the 'tags' column.

**Q7: What is the purpose of using `CountVectorizer` in this project?**

**A7:** The `CountVectorizer` was used to convert the text data in the 'tags' column into a numerical representation (a matrix of token counts). This is a crucial step for preparing the text data for the machine learning algorithm.

**Q8: What were the key parameters used when initializing `CountVectorizer`?**

**A8:**
1. `max_features=10000`: This limits the vocabulary to the top 10,000 most frequent words.
2. `stop_words='english'`: This removes common English stop words (like 'the', 'is', 'and') from the vocabulary.

**Q9: How was the numerical representation of the text data generated?**

**A9:** The `fit_transform()` method of the `CountVectorizer` was applied to the 'tags' column of the DataFrame. The resulting sparse matrix was then converted to a dense NumPy array using `toarray()`.

**Q10: What metric was used to measure the similarity between movies?**

**A10:** Cosine similarity was used to measure the similarity between the movie vectors.

**Q11: Why is cosine similarity suitable for this task?**

**A11:** Cosine similarity measures the cosine of the angle between two vectors. In the context of text data represented as vectors, it provides a measure of similarity regardless of the magnitude of the vectors, focusing on the orientation (i.e., the words they have in common).

**Q12: How was the similarity matrix generated?**

**A12:** The `cosine_similarity()` function from `sklearn.metrics.pairwise` was used with the numerical representation of the 'tags' data (the vector array) as input.

**Q13: How is a movie's index found in the DataFrame based on its title?**

**A13:** The code filters the DataFrame to find the row where the 'title' column matches the input movie title and then retrieves the index of that row using `.index[0]`. Case-insensitive matching can be done by converting both the column and input to lowercase.

**Q14: How are the top 5 most similar movies identified?**

**A14:**
1. The row corresponding to the input movie's index is taken from the similarity matrix. This row contains the similarity scores between the input movie and all other movies.
2. This list of similarity scores (paired with their original indices) is sorted in descending order based on the similarity score.
3. The top 5 entries (excluding the first one, which is the movie itself with a similarity of 1) are selected.
4. The original indices from these top entries are used to retrieve the titles of the similar movies from the DataFrame.

**Q15: Explain the `recommend` function created in the notebook.**

**A15:** The `recommend` function takes a movie title as input. It finds the index of that movie, calculates its cosine similarity to all other movies, sorts the similarities, and then prints the titles of the top 5 most similar movies (excluding the input movie itself).

**Q16: How were the processed data and the similarity matrix saved for later use?**

**A16:** The `new_data` DataFrame (containing 'sno', 'id', 'title', and 'tags') and the `similarity` matrix were saved to files named 'movies_list.pkl' and 'similarity.pkl' respectively, using Python's `pickle` module in binary write mode (`'wb'`).

**Q17: How were the saved data and similarity matrix loaded back into the notebook?**

**A17:** The `pickle.load()` function was used to load the data from 'movies_list.pkl' and 'similarity.pkl' in binary read mode (`'rb'`).

**Q18: Explain the `load_data` function.**

**A18:** The `load_data` function encapsulates the process of loading the serialized 'movies_list.pkl' DataFrame and 'similarity.pkl' matrix using `pickle.load()` and returns both loaded objects.

**Q19: Explain the `recommend_movie` function.**

**A19:** The `recommend_movie` function takes the input movie title, the movies DataFrame, and the similarity matrix as arguments. It finds the index of the input movie, calculates and sorts the similarity scores, and then prints the titles of the top 5 recommended movies (excluding the input movie itself). It also includes formatting for better readability.

**Q20: How was a serial number ('sno') column added to the loaded dataset, and why was it placed as the first column?**

**A20:** A serial number column was added by assigning a range of numbers from 1 to the total number of rows using `range(1, len(loaded_movies_list) + 1)`. It was placed as the first column by reordering the DataFrame columns using double square brackets `[['sno', 'id', 'title', 'tags']]` for better presentation.

**Q21: How was user input handled for getting movie recommendations?**

**A21:** An `ipywidgets.Text` widget was used to create an input box in the notebook. A function `on_submit` was defined to capture the value entered by the user when they submit the input, and this function was attached to the widget's `on_submit` event. The recommendation logic was then called with the user's input.

**Q22: How were the recommendations displayed in a formatted table?**

**A22:** The `prettytable` library was used to create a table with "Rank" and "Title" columns. The top 5 recommended movie titles were added row by row to the `PrettyTable` object, and then the table was printed to the console. Alternatively, pandas DataFrames were converted to HTML tables using `.to_html()` for display with borders.

**Q23: What type of machine learning task is this movie recommendation system considered?**

**A23:** This is a **Recommendation System**, specifically a **Content-Based Recommendation System**. It falls under the category of **Unsupervised Learning** because it finds patterns (similarities between movies) in unlabeled data without explicit output labels.

**Q24: What are some key takeaways from this project for an interview?**

**A24:**
1.  Understanding of data loading and initial exploration techniques in pandas.
2.  Feature engineering by combining relevant columns.
3.  Text vectorization using `CountVectorizer`.
4.  Applying cosine similarity to measure similarity between text-based features.
5.  Implementing a recommendation logic based on similarity scores.
6.  Saving and loading model components using `pickle`.
7.  Handling user input and displaying results in a user-friendly format (using widgets or tables).
8.  Ability to categorize the ML task (Recommendation System, Content-Based, Unsupervised Learning).

**Q25: What are potential improvements or next steps for this project?**

**A25:**
1.  Explore other text vectorization techniques like TF-IDF.
2.  Consider other similarity metrics.
3.  Incorporate other features like cast, director, keywords, etc., into the 'tags' or vectorization process.
4.  Implement a user interface for a more interactive experience.
5.  Address potential issues with misspelled movie titles in user input.
6.  Scale the solution for larger datasets.

# Interview Preparation: Summary, Use Cases, and Real-World Examples

This section summarizes the notebook's purpose, provides sample use cases, and lists real-world examples of the concept used, formatted as bulleted Q&A for an interview.

*   **Q: What is this notebook about?**
    *   **A:** This notebook is about building a **Content-Based Movie Recommendation System**. It focuses on recommending movies based on the similarity of their content (overview and genre).
*   **Q: Is this notebook about prediction or getting insights?**
    *   **A:** While it doesn't make a traditional prediction in the sense of forecasting a numerical value, it **predicts** which movies a user might like based on their preference for a given movie. It also provides **insights** into the similarity between movies based on their textual content.
*   **Q: What does this system predict about?**
    *   **A:** It predicts **which other movies are most similar** to a given input movie based on their textual descriptions (overview and genre).
*   **Q: Can you give a sample use case for this type of system?**
    *   **A:** When a user finishes watching a movie they enjoyed on a streaming platform, this system can recommend other movies with similar plots and genres that they might also like.
*   **Q: What are some real-world existing examples, services, or products where this concept is used?**
    *   **A:**
        *   **Streaming Services (Netflix, Amazon Prime Video, Hulu, etc.):** These platforms use content-based filtering (along with other techniques) to recommend movies and shows based on what you've watched and their descriptions/genres.
        *   **E-commerce Websites (Amazon, etc.):** "Customers who viewed this item also viewed..." sections often use content similarity (based on product descriptions, categories, etc.) to recommend related products.
        *   **Music Streaming Services (Spotify, Apple Music):** Recommending songs or artists based on the genre, tags, or descriptions of music you listen to.
        *   **News Aggregators (Google News, Apple News):** Recommending articles based on the content and topics of articles you've read.
*   **Q: What is the concept used here for?**
    *   **A:** The core concept used is **text similarity** (specifically, using vector space models and cosine similarity) to find items (movies) that have similar characteristics based on their textual metadata. This is used to **personalize recommendations** and help users discover new content.
*   **Q: What is the key technique used for measuring similarity in this notebook?**
    *   **A:** **Cosine Similarity** is used to measure the similarity between the vector representations of the movie 'tags' (combined overview and genre).
*   **Q: How is the text data transformed for similarity calculation?**
    *   **A:** The text data is transformed into numerical vectors using **CountVectorizer**, which creates a bag-of-words representation.
*   **Q: What type of machine learning is this?**
    *   **A:** This is a **Content-Based Recommendation System**, which is a form of **Unsupervised Learning** as it identifies patterns (similarities) in unlabeled data.

Here are some real-world examples of prediction and insights in machine learning, structured as Q&A for your interview preparation:

**Q: What are some real-world applications where prediction and insights from machine learning are used?**

**A:** Machine learning is widely used for both making predictions about future events and gaining insights into data to understand patterns and relationships. Here are a few examples:

1.  **Financial Services:**
    *   **Prediction:** Predicting stock prices, identifying fraudulent transactions, assessing credit risk of loan applicants.
    *   **Insights:** Understanding customer spending patterns, analyzing market trends, identifying factors that influence investment decisions.

2.  **Healthcare:**
    *   **Prediction:** Predicting disease outbreaks, identifying patients at high risk of certain conditions, forecasting patient no-shows for appointments.
    *   **Insights:** Discovering relationships between genetic factors and diseases, understanding the effectiveness of different treatments, analyzing patient demographics to improve healthcare access.

3.  **Retail and E-commerce:**
    *   **Prediction:** Predicting customer churn, forecasting demand for products, predicting which products a customer is likely to buy next (as seen in this notebook's context with movie recommendations).
    *   **Insights:** Understanding customer segmentation and behavior, analyzing sales trends, identifying popular product combinations.

4.  **Manufacturing:**
    *   **Prediction:** Predicting equipment failures (predictive maintenance), forecasting production yields, predicting product defects.
    *   **Insights:** Identifying root causes of production issues, optimizing manufacturing processes, understanding factors affecting product quality.

5.  **Marketing and Advertising:**
    *   **Prediction:** Predicting the success of a marketing campaign, identifying which customers are most likely to respond to an advertisement, predicting customer lifetime value.
    *   **Insights:** Understanding customer preferences and interests, analyzing campaign performance, segmenting customers for targeted advertising.

**Q: How do you determine if a machine learning problem is supervised, unsupervised, or another type within the AI family?**

**A:** The key factor in determining the type of machine learning problem is the nature of the data you have and the goal you want to achieve:

1.  **Supervised Learning:**
    *   **How to confirm:** You have **labeled data**, meaning your dataset includes both the input features and the corresponding desired output or target variable. The goal is to learn a mapping from inputs to outputs so you can predict the output for new, unseen inputs.
    *   **Subtypes:**
        *   **Classification:** The target variable is categorical (e.g., predicting if an email is spam or not spam, classifying an image as a cat or a dog).
        *   **Regression:** The target variable is continuous or numerical (e.g., predicting house prices, forecasting stock prices).
    *   **How this relates to prediction/insights:** Primarily used for **prediction**.

2.  **Unsupervised Learning:**
    *   **How to confirm:** You have **unlabeled data**, meaning your dataset only contains input features, and there is no predefined target output. The goal is to find hidden patterns, structures, or relationships within the data.
    *   **Subtypes:**
        *   **Clustering:** Grouping similar data points together (e.g., customer segmentation).
        *   **Dimensionality Reduction:** Reducing the number of features while retaining important information (e.g., PCA).
        *   **Association Rule Mining:** Discovering relationships between variables (e.g., "customers who bought item A also bought item B").
    *   **How this relates to prediction/insights:** Primarily used for gaining **insights** and discovering patterns, although the results of unsupervised learning can sometimes be used as features for supervised learning tasks.

3.  **Other AI Family phases (Briefly):**
    *   **Reinforcement Learning:** An agent learns to make decisions by taking actions in an environment and receiving rewards or penalties. This is used for tasks like training game-playing AI or robotics.
    *   **Deep Learning:** A subset of machine learning that uses artificial neural networks with multiple layers to learn complex patterns. Deep learning can be applied to supervised, unsupervised, and reinforcement learning tasks, especially for handling large and complex data like images, audio, and text.

**Q: Based on the notebook, what type of machine learning problem is this, and is it primarily about prediction or getting insights?**

**A:**
1.  **ML Phase/Type:** This notebook demonstrates a **Content-Based Recommendation System**. This falls under the broader category of **Unsupervised Learning**.
2.  **Prediction or Insights:** It is primarily used for **prediction** in the sense that it predicts which movies a user might like based on their input. However, the underlying process of finding similar movies based on content can also be seen as providing **insights** into the relationships between movies.

**Q: What is the prediction or insight used for in this specific movie recommendation problem, what is achieved in the real world, and what ML algorithms could be used?**

**A:**
1.  **What it's used for:** The prediction (recommending similar movies) is used to **personalize the user experience** on platforms like streaming services.
2.  **What is achieved in the real world:** By providing relevant recommendations, these systems **increase user engagement**, **improve user satisfaction**, and **drive content consumption**. They help users discover new movies they might enjoy, preventing them from getting lost in a large catalog.
3.  **ML Algorithms:**
    *   **For the vectorization (transforming text to numbers):** As seen in the notebook, **CountVectorizer** or **TF-IDF Vectorizer** are common algorithms.
    *   **For measuring similarity:** **Cosine Similarity** (used here) is a widely used metric. Other metrics like Euclidean distance could also be considered, but cosine similarity is often preferred for text data as it focuses on orientation rather than magnitude.
    *   **For the recommendation logic:** The core logic involves calculating and sorting similarity scores. While not a complex ML algorithm for the final recommendation step itself, the process relies heavily on the output of the vectorization and similarity calculation. More advanced recommendation systems might use algorithms like matrix factorization (e.g., Singular Value Decomposition) or deep learning models, but for a content-based approach based on text similarity, the steps shown are fundamental.

**Q: Finally, why do we perform predictions or gain insights in machine learning, and what is the ultimate use of these results?**

**A:** We perform predictions and gain insights in machine learning to:

1.  **Make informed decisions:** Predictions help us anticipate future events or outcomes, allowing us to make proactive decisions (e.g., adjusting stock portfolios based on price predictions, allocating resources based on demand forecasts).
2.  **Understand complex data:** Insights help us uncover hidden patterns, relationships, and anomalies in large and complex datasets that would be difficult or impossible to find manually. This understanding can lead to new discoveries, improved processes, and better strategies.
3.  **Automate tasks:** Predictions and insights enable the automation of tasks that would otherwise require human intervention (e.g., automatically flagging fraudulent transactions, automatically recommending products).
4.  **Personalize experiences:** As seen in the recommendation system, ML is used to tailor content, products, or services to individual users, improving engagement and satisfaction.
5.  **Optimize processes:** By understanding the factors that influence outcomes, we can optimize various processes (e.g., optimizing manufacturing workflows, improving marketing campaign targeting).

Ultimately, the results of predictions and insights from machine learning are used to **solve real-world problems, improve efficiency, create new opportunities, and enhance human capabilities.** They provide a data-driven approach to understanding the world and making better decisions.